version: "3.9"
services:
  postgres15:
    container_name: postgres15
    image: postgres:15-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: franchises_db
    volumes:
      - franchises_db:/var/lib/postgresql/data
    restart: always
    networks:
      - accenture
  franchises:
    container_name: franchises
    image: estarlinlopez/franchises
    #    build:
    #      context: ./
    #      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres15
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
      DB_DATABASE: franchises_db
    networks:
      - accenture
    depends_on:
      - postgres15
    restart: always
volumes:
  franchises_db:
    name: franchises_db

networks:
  accenture:
    name: accenture