server:
  servlet:
    context-path: /api/v1
  port: ${PORT:8080}
spring:
  application:
    name: franchises
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres15}:${DB_PORT:5532}/${DB_DATABASE:franchises_db}
    #url: jdbc:postgresql://${DB_HOST:192.168.1.5}:${DB_PORT:5532}/${DB_DATABASE:franchises_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      #ddl-auto: create-drop
      #ddl-auto: create-only
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect